title: Janeesh Kaur Bansal
description: Computational biologist and PhD researcher working on malaria genomics.
author: Janeesh Kaur Bansal
url: "https://JaneeshBansal.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/JaneeshBansal"
footer_text: "Janeesh Kaur Bansal"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "/publications/"
 - name: "Skills"
   link: "/skills/"
 - name: "CV"
   link: "/resume/"
 - name: "Beyond Research"
   link: "/beyond-research/"
 - name: "Contact"
   link: "/contact/"
