title: Janeesh Kaur Bansal
description: Computational biologist and PhD researcher working on malaria genomics.
url: "https://JaneeshBansal.github.io"
baseurl: ""
author: Janeesh Kaur Bansal
accent: "#0b6e69"
profile_picture: "/images/janeesh_pic.png"
tracking_id:

nav:
  - name: "About"
    link: "/"
  - name: "Research"
    link: "/publications/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Resume"
    link: "/resume/"
  - name: "Contact"
    link: "/contact/"

footer: true
footer_url: "https://github.com/JaneeshBansal"
footer_text: "Janeesh Kaur Bansal"

markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
